name: lite_logger
description: A fast, lightweight, and customizable logging utility for Dart & Flutter — with colored output, emoji icons, log filtering, and powerful formatting.
version: 0.1.0
repository: https://github.com/lamnhan066/lite_logger

environment:
  sdk: ^3.7.0

dev_dependencies:
  test: ^1.25.6
  very_good_analysis: ^8.0.0
