name: lite_logger
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/lamnhan066/lite_logger

environment:
  sdk: ^3.7.0

dev_dependencies:
  test: ^1.25.6
  very_good_analysis: ^10.0.0
